// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha3

import (
	"context"
	"reflect"

	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v2/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type VirtualServiceType struct {
	ApiVersion *string            `pulumi:"apiVersion"`
	Kind       *string            `pulumi:"kind"`
	Metadata   *metav1.ObjectMeta `pulumi:"metadata"`
	// Configuration affecting label/content routing, sni routing, etc. See more details at: https://istio.io/docs/reference/config/networking/virtual-service.html
	Spec   *VirtualServiceSpec    `pulumi:"spec"`
	Status map[string]interface{} `pulumi:"status"`
}

// VirtualServiceTypeInput is an input type that accepts VirtualServiceTypeArgs and VirtualServiceTypeOutput values.
// You can construct a concrete instance of `VirtualServiceTypeInput` via:
//
//          VirtualServiceTypeArgs{...}
type VirtualServiceTypeInput interface {
	pulumi.Input

	ToVirtualServiceTypeOutput() VirtualServiceTypeOutput
	ToVirtualServiceTypeOutputWithContext(context.Context) VirtualServiceTypeOutput
}

type VirtualServiceTypeArgs struct {
	ApiVersion pulumi.StringPtrInput     `pulumi:"apiVersion"`
	Kind       pulumi.StringPtrInput     `pulumi:"kind"`
	Metadata   metav1.ObjectMetaPtrInput `pulumi:"metadata"`
	// Configuration affecting label/content routing, sni routing, etc. See more details at: https://istio.io/docs/reference/config/networking/virtual-service.html
	Spec   VirtualServiceSpecPtrInput `pulumi:"spec"`
	Status pulumi.MapInput            `pulumi:"status"`
}

func (VirtualServiceTypeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceType)(nil)).Elem()
}

func (i VirtualServiceTypeArgs) ToVirtualServiceTypeOutput() VirtualServiceTypeOutput {
	return i.ToVirtualServiceTypeOutputWithContext(context.Background())
}

func (i VirtualServiceTypeArgs) ToVirtualServiceTypeOutputWithContext(ctx context.Context) VirtualServiceTypeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceTypeOutput)
}

type VirtualServiceTypeOutput struct{ *pulumi.OutputState }

func (VirtualServiceTypeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceType)(nil)).Elem()
}

func (o VirtualServiceTypeOutput) ToVirtualServiceTypeOutput() VirtualServiceTypeOutput {
	return o
}

func (o VirtualServiceTypeOutput) ToVirtualServiceTypeOutputWithContext(ctx context.Context) VirtualServiceTypeOutput {
	return o
}

func (o VirtualServiceTypeOutput) ApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualServiceType) *string { return v.ApiVersion }).(pulumi.StringPtrOutput)
}

func (o VirtualServiceTypeOutput) Kind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualServiceType) *string { return v.Kind }).(pulumi.StringPtrOutput)
}

func (o VirtualServiceTypeOutput) Metadata() metav1.ObjectMetaPtrOutput {
	return o.ApplyT(func(v VirtualServiceType) *metav1.ObjectMeta { return v.Metadata }).(metav1.ObjectMetaPtrOutput)
}

// Configuration affecting label/content routing, sni routing, etc. See more details at: https://istio.io/docs/reference/config/networking/virtual-service.html
func (o VirtualServiceTypeOutput) Spec() VirtualServiceSpecPtrOutput {
	return o.ApplyT(func(v VirtualServiceType) *VirtualServiceSpec { return v.Spec }).(VirtualServiceSpecPtrOutput)
}

func (o VirtualServiceTypeOutput) Status() pulumi.MapOutput {
	return o.ApplyT(func(v VirtualServiceType) map[string]interface{} { return v.Status }).(pulumi.MapOutput)
}

// Configuration affecting label/content routing, sni routing, etc. See more details at: https://istio.io/docs/reference/config/networking/virtual-service.html
type VirtualServiceSpec struct {
	// A list of namespaces to which this virtual service is exported.
	ExportTo []string `pulumi:"exportTo"`
	// The names of gateways and sidecars that should apply these routes.
	Gateways []string `pulumi:"gateways"`
	// The destination hosts to which traffic is being sent.
	Hosts []string `pulumi:"hosts"`
	// An ordered list of route rules for HTTP traffic.
	Http []VirtualServiceSpecHttp `pulumi:"http"`
}

// VirtualServiceSpecInput is an input type that accepts VirtualServiceSpecArgs and VirtualServiceSpecOutput values.
// You can construct a concrete instance of `VirtualServiceSpecInput` via:
//
//          VirtualServiceSpecArgs{...}
type VirtualServiceSpecInput interface {
	pulumi.Input

	ToVirtualServiceSpecOutput() VirtualServiceSpecOutput
	ToVirtualServiceSpecOutputWithContext(context.Context) VirtualServiceSpecOutput
}

// Configuration affecting label/content routing, sni routing, etc. See more details at: https://istio.io/docs/reference/config/networking/virtual-service.html
type VirtualServiceSpecArgs struct {
	// A list of namespaces to which this virtual service is exported.
	ExportTo pulumi.StringArrayInput `pulumi:"exportTo"`
	// The names of gateways and sidecars that should apply these routes.
	Gateways pulumi.StringArrayInput `pulumi:"gateways"`
	// The destination hosts to which traffic is being sent.
	Hosts pulumi.StringArrayInput `pulumi:"hosts"`
	// An ordered list of route rules for HTTP traffic.
	Http VirtualServiceSpecHttpArrayInput `pulumi:"http"`
}

func (VirtualServiceSpecArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpec)(nil)).Elem()
}

func (i VirtualServiceSpecArgs) ToVirtualServiceSpecOutput() VirtualServiceSpecOutput {
	return i.ToVirtualServiceSpecOutputWithContext(context.Background())
}

func (i VirtualServiceSpecArgs) ToVirtualServiceSpecOutputWithContext(ctx context.Context) VirtualServiceSpecOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecOutput)
}

func (i VirtualServiceSpecArgs) ToVirtualServiceSpecPtrOutput() VirtualServiceSpecPtrOutput {
	return i.ToVirtualServiceSpecPtrOutputWithContext(context.Background())
}

func (i VirtualServiceSpecArgs) ToVirtualServiceSpecPtrOutputWithContext(ctx context.Context) VirtualServiceSpecPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecOutput).ToVirtualServiceSpecPtrOutputWithContext(ctx)
}

// VirtualServiceSpecPtrInput is an input type that accepts VirtualServiceSpecArgs, VirtualServiceSpecPtr and VirtualServiceSpecPtrOutput values.
// You can construct a concrete instance of `VirtualServiceSpecPtrInput` via:
//
//          VirtualServiceSpecArgs{...}
//
//  or:
//
//          nil
type VirtualServiceSpecPtrInput interface {
	pulumi.Input

	ToVirtualServiceSpecPtrOutput() VirtualServiceSpecPtrOutput
	ToVirtualServiceSpecPtrOutputWithContext(context.Context) VirtualServiceSpecPtrOutput
}

type virtualServiceSpecPtrType VirtualServiceSpecArgs

func VirtualServiceSpecPtr(v *VirtualServiceSpecArgs) VirtualServiceSpecPtrInput {
	return (*virtualServiceSpecPtrType)(v)
}

func (*virtualServiceSpecPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualServiceSpec)(nil)).Elem()
}

func (i *virtualServiceSpecPtrType) ToVirtualServiceSpecPtrOutput() VirtualServiceSpecPtrOutput {
	return i.ToVirtualServiceSpecPtrOutputWithContext(context.Background())
}

func (i *virtualServiceSpecPtrType) ToVirtualServiceSpecPtrOutputWithContext(ctx context.Context) VirtualServiceSpecPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecPtrOutput)
}

// Configuration affecting label/content routing, sni routing, etc. See more details at: https://istio.io/docs/reference/config/networking/virtual-service.html
type VirtualServiceSpecOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpec)(nil)).Elem()
}

func (o VirtualServiceSpecOutput) ToVirtualServiceSpecOutput() VirtualServiceSpecOutput {
	return o
}

func (o VirtualServiceSpecOutput) ToVirtualServiceSpecOutputWithContext(ctx context.Context) VirtualServiceSpecOutput {
	return o
}

func (o VirtualServiceSpecOutput) ToVirtualServiceSpecPtrOutput() VirtualServiceSpecPtrOutput {
	return o.ToVirtualServiceSpecPtrOutputWithContext(context.Background())
}

func (o VirtualServiceSpecOutput) ToVirtualServiceSpecPtrOutputWithContext(ctx context.Context) VirtualServiceSpecPtrOutput {
	return o.ApplyT(func(v VirtualServiceSpec) *VirtualServiceSpec {
		return &v
	}).(VirtualServiceSpecPtrOutput)
}

// A list of namespaces to which this virtual service is exported.
func (o VirtualServiceSpecOutput) ExportTo() pulumi.StringArrayOutput {
	return o.ApplyT(func(v VirtualServiceSpec) []string { return v.ExportTo }).(pulumi.StringArrayOutput)
}

// The names of gateways and sidecars that should apply these routes.
func (o VirtualServiceSpecOutput) Gateways() pulumi.StringArrayOutput {
	return o.ApplyT(func(v VirtualServiceSpec) []string { return v.Gateways }).(pulumi.StringArrayOutput)
}

// The destination hosts to which traffic is being sent.
func (o VirtualServiceSpecOutput) Hosts() pulumi.StringArrayOutput {
	return o.ApplyT(func(v VirtualServiceSpec) []string { return v.Hosts }).(pulumi.StringArrayOutput)
}

// An ordered list of route rules for HTTP traffic.
func (o VirtualServiceSpecOutput) Http() VirtualServiceSpecHttpArrayOutput {
	return o.ApplyT(func(v VirtualServiceSpec) []VirtualServiceSpecHttp { return v.Http }).(VirtualServiceSpecHttpArrayOutput)
}

type VirtualServiceSpecPtrOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualServiceSpec)(nil)).Elem()
}

func (o VirtualServiceSpecPtrOutput) ToVirtualServiceSpecPtrOutput() VirtualServiceSpecPtrOutput {
	return o
}

func (o VirtualServiceSpecPtrOutput) ToVirtualServiceSpecPtrOutputWithContext(ctx context.Context) VirtualServiceSpecPtrOutput {
	return o
}

func (o VirtualServiceSpecPtrOutput) Elem() VirtualServiceSpecOutput {
	return o.ApplyT(func(v *VirtualServiceSpec) VirtualServiceSpec { return *v }).(VirtualServiceSpecOutput)
}

// A list of namespaces to which this virtual service is exported.
func (o VirtualServiceSpecPtrOutput) ExportTo() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *VirtualServiceSpec) []string {
		if v == nil {
			return nil
		}
		return v.ExportTo
	}).(pulumi.StringArrayOutput)
}

// The names of gateways and sidecars that should apply these routes.
func (o VirtualServiceSpecPtrOutput) Gateways() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *VirtualServiceSpec) []string {
		if v == nil {
			return nil
		}
		return v.Gateways
	}).(pulumi.StringArrayOutput)
}

// The destination hosts to which traffic is being sent.
func (o VirtualServiceSpecPtrOutput) Hosts() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *VirtualServiceSpec) []string {
		if v == nil {
			return nil
		}
		return v.Hosts
	}).(pulumi.StringArrayOutput)
}

// An ordered list of route rules for HTTP traffic.
func (o VirtualServiceSpecPtrOutput) Http() VirtualServiceSpecHttpArrayOutput {
	return o.ApplyT(func(v *VirtualServiceSpec) []VirtualServiceSpecHttp {
		if v == nil {
			return nil
		}
		return v.Http
	}).(VirtualServiceSpecHttpArrayOutput)
}

type VirtualServiceSpecHttp struct {
	Match []VirtualServiceSpecHttpMatch `pulumi:"match"`
	// The name assigned to the route for debugging purposes.
	Name *string `pulumi:"name"`
	// A HTTP rule can either redirect or forward (default) traffic.
	Route []VirtualServiceSpecHttpRoute `pulumi:"route"`
}

// VirtualServiceSpecHttpInput is an input type that accepts VirtualServiceSpecHttpArgs and VirtualServiceSpecHttpOutput values.
// You can construct a concrete instance of `VirtualServiceSpecHttpInput` via:
//
//          VirtualServiceSpecHttpArgs{...}
type VirtualServiceSpecHttpInput interface {
	pulumi.Input

	ToVirtualServiceSpecHttpOutput() VirtualServiceSpecHttpOutput
	ToVirtualServiceSpecHttpOutputWithContext(context.Context) VirtualServiceSpecHttpOutput
}

type VirtualServiceSpecHttpArgs struct {
	Match VirtualServiceSpecHttpMatchArrayInput `pulumi:"match"`
	// The name assigned to the route for debugging purposes.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// A HTTP rule can either redirect or forward (default) traffic.
	Route VirtualServiceSpecHttpRouteArrayInput `pulumi:"route"`
}

func (VirtualServiceSpecHttpArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttp)(nil)).Elem()
}

func (i VirtualServiceSpecHttpArgs) ToVirtualServiceSpecHttpOutput() VirtualServiceSpecHttpOutput {
	return i.ToVirtualServiceSpecHttpOutputWithContext(context.Background())
}

func (i VirtualServiceSpecHttpArgs) ToVirtualServiceSpecHttpOutputWithContext(ctx context.Context) VirtualServiceSpecHttpOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpOutput)
}

// VirtualServiceSpecHttpArrayInput is an input type that accepts VirtualServiceSpecHttpArray and VirtualServiceSpecHttpArrayOutput values.
// You can construct a concrete instance of `VirtualServiceSpecHttpArrayInput` via:
//
//          VirtualServiceSpecHttpArray{ VirtualServiceSpecHttpArgs{...} }
type VirtualServiceSpecHttpArrayInput interface {
	pulumi.Input

	ToVirtualServiceSpecHttpArrayOutput() VirtualServiceSpecHttpArrayOutput
	ToVirtualServiceSpecHttpArrayOutputWithContext(context.Context) VirtualServiceSpecHttpArrayOutput
}

type VirtualServiceSpecHttpArray []VirtualServiceSpecHttpInput

func (VirtualServiceSpecHttpArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]VirtualServiceSpecHttp)(nil)).Elem()
}

func (i VirtualServiceSpecHttpArray) ToVirtualServiceSpecHttpArrayOutput() VirtualServiceSpecHttpArrayOutput {
	return i.ToVirtualServiceSpecHttpArrayOutputWithContext(context.Background())
}

func (i VirtualServiceSpecHttpArray) ToVirtualServiceSpecHttpArrayOutputWithContext(ctx context.Context) VirtualServiceSpecHttpArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpArrayOutput)
}

type VirtualServiceSpecHttpOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecHttpOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttp)(nil)).Elem()
}

func (o VirtualServiceSpecHttpOutput) ToVirtualServiceSpecHttpOutput() VirtualServiceSpecHttpOutput {
	return o
}

func (o VirtualServiceSpecHttpOutput) ToVirtualServiceSpecHttpOutputWithContext(ctx context.Context) VirtualServiceSpecHttpOutput {
	return o
}

func (o VirtualServiceSpecHttpOutput) Match() VirtualServiceSpecHttpMatchArrayOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttp) []VirtualServiceSpecHttpMatch { return v.Match }).(VirtualServiceSpecHttpMatchArrayOutput)
}

// The name assigned to the route for debugging purposes.
func (o VirtualServiceSpecHttpOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttp) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// A HTTP rule can either redirect or forward (default) traffic.
func (o VirtualServiceSpecHttpOutput) Route() VirtualServiceSpecHttpRouteArrayOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttp) []VirtualServiceSpecHttpRoute { return v.Route }).(VirtualServiceSpecHttpRouteArrayOutput)
}

type VirtualServiceSpecHttpArrayOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecHttpArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]VirtualServiceSpecHttp)(nil)).Elem()
}

func (o VirtualServiceSpecHttpArrayOutput) ToVirtualServiceSpecHttpArrayOutput() VirtualServiceSpecHttpArrayOutput {
	return o
}

func (o VirtualServiceSpecHttpArrayOutput) ToVirtualServiceSpecHttpArrayOutputWithContext(ctx context.Context) VirtualServiceSpecHttpArrayOutput {
	return o
}

func (o VirtualServiceSpecHttpArrayOutput) Index(i pulumi.IntInput) VirtualServiceSpecHttpOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) VirtualServiceSpecHttp {
		return vs[0].([]VirtualServiceSpecHttp)[vs[1].(int)]
	}).(VirtualServiceSpecHttpOutput)
}

type VirtualServiceSpecHttpMatch struct {
	Authority interface{} `pulumi:"authority"`
	// Names of gateways where the rule should be applied.
	Gateways []string               `pulumi:"gateways"`
	Headers  map[string]interface{} `pulumi:"headers"`
	// Flag to specify whether the URI matching should be case-insensitive.
	IgnoreUriCase *bool       `pulumi:"ignoreUriCase"`
	Method        interface{} `pulumi:"method"`
	// The name assigned to a match.
	Name *string `pulumi:"name"`
	// Specifies the ports on the host that is being addressed.
	Port *int `pulumi:"port"`
	// Query parameters for matching.
	QueryParams  map[string]interface{} `pulumi:"queryParams"`
	Scheme       interface{}            `pulumi:"scheme"`
	SourceLabels map[string]string      `pulumi:"sourceLabels"`
	// Source namespace constraining the applicability of a rule to workloads in that namespace.
	SourceNamespace *string     `pulumi:"sourceNamespace"`
	Uri             interface{} `pulumi:"uri"`
	// withoutHeader has the same syntax with the header, but has opposite meaning.
	WithoutHeaders map[string]interface{} `pulumi:"withoutHeaders"`
}

// VirtualServiceSpecHttpMatchInput is an input type that accepts VirtualServiceSpecHttpMatchArgs and VirtualServiceSpecHttpMatchOutput values.
// You can construct a concrete instance of `VirtualServiceSpecHttpMatchInput` via:
//
//          VirtualServiceSpecHttpMatchArgs{...}
type VirtualServiceSpecHttpMatchInput interface {
	pulumi.Input

	ToVirtualServiceSpecHttpMatchOutput() VirtualServiceSpecHttpMatchOutput
	ToVirtualServiceSpecHttpMatchOutputWithContext(context.Context) VirtualServiceSpecHttpMatchOutput
}

type VirtualServiceSpecHttpMatchArgs struct {
	Authority pulumi.Input `pulumi:"authority"`
	// Names of gateways where the rule should be applied.
	Gateways pulumi.StringArrayInput `pulumi:"gateways"`
	Headers  pulumi.MapInput         `pulumi:"headers"`
	// Flag to specify whether the URI matching should be case-insensitive.
	IgnoreUriCase pulumi.BoolPtrInput `pulumi:"ignoreUriCase"`
	Method        pulumi.Input        `pulumi:"method"`
	// The name assigned to a match.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// Specifies the ports on the host that is being addressed.
	Port pulumi.IntPtrInput `pulumi:"port"`
	// Query parameters for matching.
	QueryParams  pulumi.MapInput       `pulumi:"queryParams"`
	Scheme       pulumi.Input          `pulumi:"scheme"`
	SourceLabels pulumi.StringMapInput `pulumi:"sourceLabels"`
	// Source namespace constraining the applicability of a rule to workloads in that namespace.
	SourceNamespace pulumi.StringPtrInput `pulumi:"sourceNamespace"`
	Uri             pulumi.Input          `pulumi:"uri"`
	// withoutHeader has the same syntax with the header, but has opposite meaning.
	WithoutHeaders pulumi.MapInput `pulumi:"withoutHeaders"`
}

func (VirtualServiceSpecHttpMatchArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpMatch)(nil)).Elem()
}

func (i VirtualServiceSpecHttpMatchArgs) ToVirtualServiceSpecHttpMatchOutput() VirtualServiceSpecHttpMatchOutput {
	return i.ToVirtualServiceSpecHttpMatchOutputWithContext(context.Background())
}

func (i VirtualServiceSpecHttpMatchArgs) ToVirtualServiceSpecHttpMatchOutputWithContext(ctx context.Context) VirtualServiceSpecHttpMatchOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpMatchOutput)
}

// VirtualServiceSpecHttpMatchArrayInput is an input type that accepts VirtualServiceSpecHttpMatchArray and VirtualServiceSpecHttpMatchArrayOutput values.
// You can construct a concrete instance of `VirtualServiceSpecHttpMatchArrayInput` via:
//
//          VirtualServiceSpecHttpMatchArray{ VirtualServiceSpecHttpMatchArgs{...} }
type VirtualServiceSpecHttpMatchArrayInput interface {
	pulumi.Input

	ToVirtualServiceSpecHttpMatchArrayOutput() VirtualServiceSpecHttpMatchArrayOutput
	ToVirtualServiceSpecHttpMatchArrayOutputWithContext(context.Context) VirtualServiceSpecHttpMatchArrayOutput
}

type VirtualServiceSpecHttpMatchArray []VirtualServiceSpecHttpMatchInput

func (VirtualServiceSpecHttpMatchArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]VirtualServiceSpecHttpMatch)(nil)).Elem()
}

func (i VirtualServiceSpecHttpMatchArray) ToVirtualServiceSpecHttpMatchArrayOutput() VirtualServiceSpecHttpMatchArrayOutput {
	return i.ToVirtualServiceSpecHttpMatchArrayOutputWithContext(context.Background())
}

func (i VirtualServiceSpecHttpMatchArray) ToVirtualServiceSpecHttpMatchArrayOutputWithContext(ctx context.Context) VirtualServiceSpecHttpMatchArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpMatchArrayOutput)
}

type VirtualServiceSpecHttpMatchOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecHttpMatchOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpMatch)(nil)).Elem()
}

func (o VirtualServiceSpecHttpMatchOutput) ToVirtualServiceSpecHttpMatchOutput() VirtualServiceSpecHttpMatchOutput {
	return o
}

func (o VirtualServiceSpecHttpMatchOutput) ToVirtualServiceSpecHttpMatchOutputWithContext(ctx context.Context) VirtualServiceSpecHttpMatchOutput {
	return o
}

func (o VirtualServiceSpecHttpMatchOutput) Authority() pulumi.AnyOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpMatch) interface{} { return v.Authority }).(pulumi.AnyOutput)
}

// Names of gateways where the rule should be applied.
func (o VirtualServiceSpecHttpMatchOutput) Gateways() pulumi.StringArrayOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpMatch) []string { return v.Gateways }).(pulumi.StringArrayOutput)
}

func (o VirtualServiceSpecHttpMatchOutput) Headers() pulumi.MapOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpMatch) map[string]interface{} { return v.Headers }).(pulumi.MapOutput)
}

// Flag to specify whether the URI matching should be case-insensitive.
func (o VirtualServiceSpecHttpMatchOutput) IgnoreUriCase() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpMatch) *bool { return v.IgnoreUriCase }).(pulumi.BoolPtrOutput)
}

func (o VirtualServiceSpecHttpMatchOutput) Method() pulumi.AnyOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpMatch) interface{} { return v.Method }).(pulumi.AnyOutput)
}

// The name assigned to a match.
func (o VirtualServiceSpecHttpMatchOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpMatch) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// Specifies the ports on the host that is being addressed.
func (o VirtualServiceSpecHttpMatchOutput) Port() pulumi.IntPtrOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpMatch) *int { return v.Port }).(pulumi.IntPtrOutput)
}

// Query parameters for matching.
func (o VirtualServiceSpecHttpMatchOutput) QueryParams() pulumi.MapOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpMatch) map[string]interface{} { return v.QueryParams }).(pulumi.MapOutput)
}

func (o VirtualServiceSpecHttpMatchOutput) Scheme() pulumi.AnyOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpMatch) interface{} { return v.Scheme }).(pulumi.AnyOutput)
}

func (o VirtualServiceSpecHttpMatchOutput) SourceLabels() pulumi.StringMapOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpMatch) map[string]string { return v.SourceLabels }).(pulumi.StringMapOutput)
}

// Source namespace constraining the applicability of a rule to workloads in that namespace.
func (o VirtualServiceSpecHttpMatchOutput) SourceNamespace() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpMatch) *string { return v.SourceNamespace }).(pulumi.StringPtrOutput)
}

func (o VirtualServiceSpecHttpMatchOutput) Uri() pulumi.AnyOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpMatch) interface{} { return v.Uri }).(pulumi.AnyOutput)
}

// withoutHeader has the same syntax with the header, but has opposite meaning.
func (o VirtualServiceSpecHttpMatchOutput) WithoutHeaders() pulumi.MapOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpMatch) map[string]interface{} { return v.WithoutHeaders }).(pulumi.MapOutput)
}

type VirtualServiceSpecHttpMatchArrayOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecHttpMatchArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]VirtualServiceSpecHttpMatch)(nil)).Elem()
}

func (o VirtualServiceSpecHttpMatchArrayOutput) ToVirtualServiceSpecHttpMatchArrayOutput() VirtualServiceSpecHttpMatchArrayOutput {
	return o
}

func (o VirtualServiceSpecHttpMatchArrayOutput) ToVirtualServiceSpecHttpMatchArrayOutputWithContext(ctx context.Context) VirtualServiceSpecHttpMatchArrayOutput {
	return o
}

func (o VirtualServiceSpecHttpMatchArrayOutput) Index(i pulumi.IntInput) VirtualServiceSpecHttpMatchOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) VirtualServiceSpecHttpMatch {
		return vs[0].([]VirtualServiceSpecHttpMatch)[vs[1].(int)]
	}).(VirtualServiceSpecHttpMatchOutput)
}

type VirtualServiceSpecHttpMatchHeaders struct {
}

// VirtualServiceSpecHttpMatchHeadersInput is an input type that accepts VirtualServiceSpecHttpMatchHeadersArgs and VirtualServiceSpecHttpMatchHeadersOutput values.
// You can construct a concrete instance of `VirtualServiceSpecHttpMatchHeadersInput` via:
//
//          VirtualServiceSpecHttpMatchHeadersArgs{...}
type VirtualServiceSpecHttpMatchHeadersInput interface {
	pulumi.Input

	ToVirtualServiceSpecHttpMatchHeadersOutput() VirtualServiceSpecHttpMatchHeadersOutput
	ToVirtualServiceSpecHttpMatchHeadersOutputWithContext(context.Context) VirtualServiceSpecHttpMatchHeadersOutput
}

type VirtualServiceSpecHttpMatchHeadersArgs struct {
}

func (VirtualServiceSpecHttpMatchHeadersArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpMatchHeaders)(nil)).Elem()
}

func (i VirtualServiceSpecHttpMatchHeadersArgs) ToVirtualServiceSpecHttpMatchHeadersOutput() VirtualServiceSpecHttpMatchHeadersOutput {
	return i.ToVirtualServiceSpecHttpMatchHeadersOutputWithContext(context.Background())
}

func (i VirtualServiceSpecHttpMatchHeadersArgs) ToVirtualServiceSpecHttpMatchHeadersOutputWithContext(ctx context.Context) VirtualServiceSpecHttpMatchHeadersOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpMatchHeadersOutput)
}

type VirtualServiceSpecHttpMatchHeadersOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecHttpMatchHeadersOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpMatchHeaders)(nil)).Elem()
}

func (o VirtualServiceSpecHttpMatchHeadersOutput) ToVirtualServiceSpecHttpMatchHeadersOutput() VirtualServiceSpecHttpMatchHeadersOutput {
	return o
}

func (o VirtualServiceSpecHttpMatchHeadersOutput) ToVirtualServiceSpecHttpMatchHeadersOutputWithContext(ctx context.Context) VirtualServiceSpecHttpMatchHeadersOutput {
	return o
}

// Query parameters for matching.
type VirtualServiceSpecHttpMatchQueryParams struct {
}

// VirtualServiceSpecHttpMatchQueryParamsInput is an input type that accepts VirtualServiceSpecHttpMatchQueryParamsArgs and VirtualServiceSpecHttpMatchQueryParamsOutput values.
// You can construct a concrete instance of `VirtualServiceSpecHttpMatchQueryParamsInput` via:
//
//          VirtualServiceSpecHttpMatchQueryParamsArgs{...}
type VirtualServiceSpecHttpMatchQueryParamsInput interface {
	pulumi.Input

	ToVirtualServiceSpecHttpMatchQueryParamsOutput() VirtualServiceSpecHttpMatchQueryParamsOutput
	ToVirtualServiceSpecHttpMatchQueryParamsOutputWithContext(context.Context) VirtualServiceSpecHttpMatchQueryParamsOutput
}

// Query parameters for matching.
type VirtualServiceSpecHttpMatchQueryParamsArgs struct {
}

func (VirtualServiceSpecHttpMatchQueryParamsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpMatchQueryParams)(nil)).Elem()
}

func (i VirtualServiceSpecHttpMatchQueryParamsArgs) ToVirtualServiceSpecHttpMatchQueryParamsOutput() VirtualServiceSpecHttpMatchQueryParamsOutput {
	return i.ToVirtualServiceSpecHttpMatchQueryParamsOutputWithContext(context.Background())
}

func (i VirtualServiceSpecHttpMatchQueryParamsArgs) ToVirtualServiceSpecHttpMatchQueryParamsOutputWithContext(ctx context.Context) VirtualServiceSpecHttpMatchQueryParamsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpMatchQueryParamsOutput)
}

// Query parameters for matching.
type VirtualServiceSpecHttpMatchQueryParamsOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecHttpMatchQueryParamsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpMatchQueryParams)(nil)).Elem()
}

func (o VirtualServiceSpecHttpMatchQueryParamsOutput) ToVirtualServiceSpecHttpMatchQueryParamsOutput() VirtualServiceSpecHttpMatchQueryParamsOutput {
	return o
}

func (o VirtualServiceSpecHttpMatchQueryParamsOutput) ToVirtualServiceSpecHttpMatchQueryParamsOutputWithContext(ctx context.Context) VirtualServiceSpecHttpMatchQueryParamsOutput {
	return o
}

type VirtualServiceSpecHttpMatchSourceLabels struct {
}

// VirtualServiceSpecHttpMatchSourceLabelsInput is an input type that accepts VirtualServiceSpecHttpMatchSourceLabelsArgs and VirtualServiceSpecHttpMatchSourceLabelsOutput values.
// You can construct a concrete instance of `VirtualServiceSpecHttpMatchSourceLabelsInput` via:
//
//          VirtualServiceSpecHttpMatchSourceLabelsArgs{...}
type VirtualServiceSpecHttpMatchSourceLabelsInput interface {
	pulumi.Input

	ToVirtualServiceSpecHttpMatchSourceLabelsOutput() VirtualServiceSpecHttpMatchSourceLabelsOutput
	ToVirtualServiceSpecHttpMatchSourceLabelsOutputWithContext(context.Context) VirtualServiceSpecHttpMatchSourceLabelsOutput
}

type VirtualServiceSpecHttpMatchSourceLabelsArgs struct {
}

func (VirtualServiceSpecHttpMatchSourceLabelsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpMatchSourceLabels)(nil)).Elem()
}

func (i VirtualServiceSpecHttpMatchSourceLabelsArgs) ToVirtualServiceSpecHttpMatchSourceLabelsOutput() VirtualServiceSpecHttpMatchSourceLabelsOutput {
	return i.ToVirtualServiceSpecHttpMatchSourceLabelsOutputWithContext(context.Background())
}

func (i VirtualServiceSpecHttpMatchSourceLabelsArgs) ToVirtualServiceSpecHttpMatchSourceLabelsOutputWithContext(ctx context.Context) VirtualServiceSpecHttpMatchSourceLabelsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpMatchSourceLabelsOutput)
}

type VirtualServiceSpecHttpMatchSourceLabelsOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecHttpMatchSourceLabelsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpMatchSourceLabels)(nil)).Elem()
}

func (o VirtualServiceSpecHttpMatchSourceLabelsOutput) ToVirtualServiceSpecHttpMatchSourceLabelsOutput() VirtualServiceSpecHttpMatchSourceLabelsOutput {
	return o
}

func (o VirtualServiceSpecHttpMatchSourceLabelsOutput) ToVirtualServiceSpecHttpMatchSourceLabelsOutputWithContext(ctx context.Context) VirtualServiceSpecHttpMatchSourceLabelsOutput {
	return o
}

// withoutHeader has the same syntax with the header, but has opposite meaning.
type VirtualServiceSpecHttpMatchWithoutHeaders struct {
}

// VirtualServiceSpecHttpMatchWithoutHeadersInput is an input type that accepts VirtualServiceSpecHttpMatchWithoutHeadersArgs and VirtualServiceSpecHttpMatchWithoutHeadersOutput values.
// You can construct a concrete instance of `VirtualServiceSpecHttpMatchWithoutHeadersInput` via:
//
//          VirtualServiceSpecHttpMatchWithoutHeadersArgs{...}
type VirtualServiceSpecHttpMatchWithoutHeadersInput interface {
	pulumi.Input

	ToVirtualServiceSpecHttpMatchWithoutHeadersOutput() VirtualServiceSpecHttpMatchWithoutHeadersOutput
	ToVirtualServiceSpecHttpMatchWithoutHeadersOutputWithContext(context.Context) VirtualServiceSpecHttpMatchWithoutHeadersOutput
}

// withoutHeader has the same syntax with the header, but has opposite meaning.
type VirtualServiceSpecHttpMatchWithoutHeadersArgs struct {
}

func (VirtualServiceSpecHttpMatchWithoutHeadersArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpMatchWithoutHeaders)(nil)).Elem()
}

func (i VirtualServiceSpecHttpMatchWithoutHeadersArgs) ToVirtualServiceSpecHttpMatchWithoutHeadersOutput() VirtualServiceSpecHttpMatchWithoutHeadersOutput {
	return i.ToVirtualServiceSpecHttpMatchWithoutHeadersOutputWithContext(context.Background())
}

func (i VirtualServiceSpecHttpMatchWithoutHeadersArgs) ToVirtualServiceSpecHttpMatchWithoutHeadersOutputWithContext(ctx context.Context) VirtualServiceSpecHttpMatchWithoutHeadersOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpMatchWithoutHeadersOutput)
}

// withoutHeader has the same syntax with the header, but has opposite meaning.
type VirtualServiceSpecHttpMatchWithoutHeadersOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecHttpMatchWithoutHeadersOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpMatchWithoutHeaders)(nil)).Elem()
}

func (o VirtualServiceSpecHttpMatchWithoutHeadersOutput) ToVirtualServiceSpecHttpMatchWithoutHeadersOutput() VirtualServiceSpecHttpMatchWithoutHeadersOutput {
	return o
}

func (o VirtualServiceSpecHttpMatchWithoutHeadersOutput) ToVirtualServiceSpecHttpMatchWithoutHeadersOutputWithContext(ctx context.Context) VirtualServiceSpecHttpMatchWithoutHeadersOutput {
	return o
}

type VirtualServiceSpecHttpRoute struct {
	Destination *VirtualServiceSpecHttpRouteDestination `pulumi:"destination"`
	Headers     *VirtualServiceSpecHttpRouteHeaders     `pulumi:"headers"`
	Weight      *int                                    `pulumi:"weight"`
}

// VirtualServiceSpecHttpRouteInput is an input type that accepts VirtualServiceSpecHttpRouteArgs and VirtualServiceSpecHttpRouteOutput values.
// You can construct a concrete instance of `VirtualServiceSpecHttpRouteInput` via:
//
//          VirtualServiceSpecHttpRouteArgs{...}
type VirtualServiceSpecHttpRouteInput interface {
	pulumi.Input

	ToVirtualServiceSpecHttpRouteOutput() VirtualServiceSpecHttpRouteOutput
	ToVirtualServiceSpecHttpRouteOutputWithContext(context.Context) VirtualServiceSpecHttpRouteOutput
}

type VirtualServiceSpecHttpRouteArgs struct {
	Destination VirtualServiceSpecHttpRouteDestinationPtrInput `pulumi:"destination"`
	Headers     VirtualServiceSpecHttpRouteHeadersPtrInput     `pulumi:"headers"`
	Weight      pulumi.IntPtrInput                             `pulumi:"weight"`
}

func (VirtualServiceSpecHttpRouteArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpRoute)(nil)).Elem()
}

func (i VirtualServiceSpecHttpRouteArgs) ToVirtualServiceSpecHttpRouteOutput() VirtualServiceSpecHttpRouteOutput {
	return i.ToVirtualServiceSpecHttpRouteOutputWithContext(context.Background())
}

func (i VirtualServiceSpecHttpRouteArgs) ToVirtualServiceSpecHttpRouteOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpRouteOutput)
}

// VirtualServiceSpecHttpRouteArrayInput is an input type that accepts VirtualServiceSpecHttpRouteArray and VirtualServiceSpecHttpRouteArrayOutput values.
// You can construct a concrete instance of `VirtualServiceSpecHttpRouteArrayInput` via:
//
//          VirtualServiceSpecHttpRouteArray{ VirtualServiceSpecHttpRouteArgs{...} }
type VirtualServiceSpecHttpRouteArrayInput interface {
	pulumi.Input

	ToVirtualServiceSpecHttpRouteArrayOutput() VirtualServiceSpecHttpRouteArrayOutput
	ToVirtualServiceSpecHttpRouteArrayOutputWithContext(context.Context) VirtualServiceSpecHttpRouteArrayOutput
}

type VirtualServiceSpecHttpRouteArray []VirtualServiceSpecHttpRouteInput

func (VirtualServiceSpecHttpRouteArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]VirtualServiceSpecHttpRoute)(nil)).Elem()
}

func (i VirtualServiceSpecHttpRouteArray) ToVirtualServiceSpecHttpRouteArrayOutput() VirtualServiceSpecHttpRouteArrayOutput {
	return i.ToVirtualServiceSpecHttpRouteArrayOutputWithContext(context.Background())
}

func (i VirtualServiceSpecHttpRouteArray) ToVirtualServiceSpecHttpRouteArrayOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpRouteArrayOutput)
}

type VirtualServiceSpecHttpRouteOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecHttpRouteOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpRoute)(nil)).Elem()
}

func (o VirtualServiceSpecHttpRouteOutput) ToVirtualServiceSpecHttpRouteOutput() VirtualServiceSpecHttpRouteOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteOutput) ToVirtualServiceSpecHttpRouteOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteOutput) Destination() VirtualServiceSpecHttpRouteDestinationPtrOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpRoute) *VirtualServiceSpecHttpRouteDestination { return v.Destination }).(VirtualServiceSpecHttpRouteDestinationPtrOutput)
}

func (o VirtualServiceSpecHttpRouteOutput) Headers() VirtualServiceSpecHttpRouteHeadersPtrOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpRoute) *VirtualServiceSpecHttpRouteHeaders { return v.Headers }).(VirtualServiceSpecHttpRouteHeadersPtrOutput)
}

func (o VirtualServiceSpecHttpRouteOutput) Weight() pulumi.IntPtrOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpRoute) *int { return v.Weight }).(pulumi.IntPtrOutput)
}

type VirtualServiceSpecHttpRouteArrayOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecHttpRouteArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]VirtualServiceSpecHttpRoute)(nil)).Elem()
}

func (o VirtualServiceSpecHttpRouteArrayOutput) ToVirtualServiceSpecHttpRouteArrayOutput() VirtualServiceSpecHttpRouteArrayOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteArrayOutput) ToVirtualServiceSpecHttpRouteArrayOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteArrayOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteArrayOutput) Index(i pulumi.IntInput) VirtualServiceSpecHttpRouteOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) VirtualServiceSpecHttpRoute {
		return vs[0].([]VirtualServiceSpecHttpRoute)[vs[1].(int)]
	}).(VirtualServiceSpecHttpRouteOutput)
}

type VirtualServiceSpecHttpRouteDestination struct {
	// The name of a service from the service registry.
	Host *string `pulumi:"host"`
	// Specifies the port on the host that is being addressed.
	Port *VirtualServiceSpecHttpRouteDestinationPort `pulumi:"port"`
	// The name of a subset within the service.
	Subset *string `pulumi:"subset"`
}

// VirtualServiceSpecHttpRouteDestinationInput is an input type that accepts VirtualServiceSpecHttpRouteDestinationArgs and VirtualServiceSpecHttpRouteDestinationOutput values.
// You can construct a concrete instance of `VirtualServiceSpecHttpRouteDestinationInput` via:
//
//          VirtualServiceSpecHttpRouteDestinationArgs{...}
type VirtualServiceSpecHttpRouteDestinationInput interface {
	pulumi.Input

	ToVirtualServiceSpecHttpRouteDestinationOutput() VirtualServiceSpecHttpRouteDestinationOutput
	ToVirtualServiceSpecHttpRouteDestinationOutputWithContext(context.Context) VirtualServiceSpecHttpRouteDestinationOutput
}

type VirtualServiceSpecHttpRouteDestinationArgs struct {
	// The name of a service from the service registry.
	Host pulumi.StringPtrInput `pulumi:"host"`
	// Specifies the port on the host that is being addressed.
	Port VirtualServiceSpecHttpRouteDestinationPortPtrInput `pulumi:"port"`
	// The name of a subset within the service.
	Subset pulumi.StringPtrInput `pulumi:"subset"`
}

func (VirtualServiceSpecHttpRouteDestinationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpRouteDestination)(nil)).Elem()
}

func (i VirtualServiceSpecHttpRouteDestinationArgs) ToVirtualServiceSpecHttpRouteDestinationOutput() VirtualServiceSpecHttpRouteDestinationOutput {
	return i.ToVirtualServiceSpecHttpRouteDestinationOutputWithContext(context.Background())
}

func (i VirtualServiceSpecHttpRouteDestinationArgs) ToVirtualServiceSpecHttpRouteDestinationOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteDestinationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpRouteDestinationOutput)
}

func (i VirtualServiceSpecHttpRouteDestinationArgs) ToVirtualServiceSpecHttpRouteDestinationPtrOutput() VirtualServiceSpecHttpRouteDestinationPtrOutput {
	return i.ToVirtualServiceSpecHttpRouteDestinationPtrOutputWithContext(context.Background())
}

func (i VirtualServiceSpecHttpRouteDestinationArgs) ToVirtualServiceSpecHttpRouteDestinationPtrOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteDestinationPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpRouteDestinationOutput).ToVirtualServiceSpecHttpRouteDestinationPtrOutputWithContext(ctx)
}

// VirtualServiceSpecHttpRouteDestinationPtrInput is an input type that accepts VirtualServiceSpecHttpRouteDestinationArgs, VirtualServiceSpecHttpRouteDestinationPtr and VirtualServiceSpecHttpRouteDestinationPtrOutput values.
// You can construct a concrete instance of `VirtualServiceSpecHttpRouteDestinationPtrInput` via:
//
//          VirtualServiceSpecHttpRouteDestinationArgs{...}
//
//  or:
//
//          nil
type VirtualServiceSpecHttpRouteDestinationPtrInput interface {
	pulumi.Input

	ToVirtualServiceSpecHttpRouteDestinationPtrOutput() VirtualServiceSpecHttpRouteDestinationPtrOutput
	ToVirtualServiceSpecHttpRouteDestinationPtrOutputWithContext(context.Context) VirtualServiceSpecHttpRouteDestinationPtrOutput
}

type virtualServiceSpecHttpRouteDestinationPtrType VirtualServiceSpecHttpRouteDestinationArgs

func VirtualServiceSpecHttpRouteDestinationPtr(v *VirtualServiceSpecHttpRouteDestinationArgs) VirtualServiceSpecHttpRouteDestinationPtrInput {
	return (*virtualServiceSpecHttpRouteDestinationPtrType)(v)
}

func (*virtualServiceSpecHttpRouteDestinationPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualServiceSpecHttpRouteDestination)(nil)).Elem()
}

func (i *virtualServiceSpecHttpRouteDestinationPtrType) ToVirtualServiceSpecHttpRouteDestinationPtrOutput() VirtualServiceSpecHttpRouteDestinationPtrOutput {
	return i.ToVirtualServiceSpecHttpRouteDestinationPtrOutputWithContext(context.Background())
}

func (i *virtualServiceSpecHttpRouteDestinationPtrType) ToVirtualServiceSpecHttpRouteDestinationPtrOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteDestinationPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpRouteDestinationPtrOutput)
}

type VirtualServiceSpecHttpRouteDestinationOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecHttpRouteDestinationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpRouteDestination)(nil)).Elem()
}

func (o VirtualServiceSpecHttpRouteDestinationOutput) ToVirtualServiceSpecHttpRouteDestinationOutput() VirtualServiceSpecHttpRouteDestinationOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteDestinationOutput) ToVirtualServiceSpecHttpRouteDestinationOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteDestinationOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteDestinationOutput) ToVirtualServiceSpecHttpRouteDestinationPtrOutput() VirtualServiceSpecHttpRouteDestinationPtrOutput {
	return o.ToVirtualServiceSpecHttpRouteDestinationPtrOutputWithContext(context.Background())
}

func (o VirtualServiceSpecHttpRouteDestinationOutput) ToVirtualServiceSpecHttpRouteDestinationPtrOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteDestinationPtrOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpRouteDestination) *VirtualServiceSpecHttpRouteDestination {
		return &v
	}).(VirtualServiceSpecHttpRouteDestinationPtrOutput)
}

// The name of a service from the service registry.
func (o VirtualServiceSpecHttpRouteDestinationOutput) Host() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpRouteDestination) *string { return v.Host }).(pulumi.StringPtrOutput)
}

// Specifies the port on the host that is being addressed.
func (o VirtualServiceSpecHttpRouteDestinationOutput) Port() VirtualServiceSpecHttpRouteDestinationPortPtrOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpRouteDestination) *VirtualServiceSpecHttpRouteDestinationPort {
		return v.Port
	}).(VirtualServiceSpecHttpRouteDestinationPortPtrOutput)
}

// The name of a subset within the service.
func (o VirtualServiceSpecHttpRouteDestinationOutput) Subset() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpRouteDestination) *string { return v.Subset }).(pulumi.StringPtrOutput)
}

type VirtualServiceSpecHttpRouteDestinationPtrOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecHttpRouteDestinationPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualServiceSpecHttpRouteDestination)(nil)).Elem()
}

func (o VirtualServiceSpecHttpRouteDestinationPtrOutput) ToVirtualServiceSpecHttpRouteDestinationPtrOutput() VirtualServiceSpecHttpRouteDestinationPtrOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteDestinationPtrOutput) ToVirtualServiceSpecHttpRouteDestinationPtrOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteDestinationPtrOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteDestinationPtrOutput) Elem() VirtualServiceSpecHttpRouteDestinationOutput {
	return o.ApplyT(func(v *VirtualServiceSpecHttpRouteDestination) VirtualServiceSpecHttpRouteDestination { return *v }).(VirtualServiceSpecHttpRouteDestinationOutput)
}

// The name of a service from the service registry.
func (o VirtualServiceSpecHttpRouteDestinationPtrOutput) Host() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VirtualServiceSpecHttpRouteDestination) *string {
		if v == nil {
			return nil
		}
		return v.Host
	}).(pulumi.StringPtrOutput)
}

// Specifies the port on the host that is being addressed.
func (o VirtualServiceSpecHttpRouteDestinationPtrOutput) Port() VirtualServiceSpecHttpRouteDestinationPortPtrOutput {
	return o.ApplyT(func(v *VirtualServiceSpecHttpRouteDestination) *VirtualServiceSpecHttpRouteDestinationPort {
		if v == nil {
			return nil
		}
		return v.Port
	}).(VirtualServiceSpecHttpRouteDestinationPortPtrOutput)
}

// The name of a subset within the service.
func (o VirtualServiceSpecHttpRouteDestinationPtrOutput) Subset() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VirtualServiceSpecHttpRouteDestination) *string {
		if v == nil {
			return nil
		}
		return v.Subset
	}).(pulumi.StringPtrOutput)
}

// Specifies the port on the host that is being addressed.
type VirtualServiceSpecHttpRouteDestinationPort struct {
	Number *int `pulumi:"number"`
}

// VirtualServiceSpecHttpRouteDestinationPortInput is an input type that accepts VirtualServiceSpecHttpRouteDestinationPortArgs and VirtualServiceSpecHttpRouteDestinationPortOutput values.
// You can construct a concrete instance of `VirtualServiceSpecHttpRouteDestinationPortInput` via:
//
//          VirtualServiceSpecHttpRouteDestinationPortArgs{...}
type VirtualServiceSpecHttpRouteDestinationPortInput interface {
	pulumi.Input

	ToVirtualServiceSpecHttpRouteDestinationPortOutput() VirtualServiceSpecHttpRouteDestinationPortOutput
	ToVirtualServiceSpecHttpRouteDestinationPortOutputWithContext(context.Context) VirtualServiceSpecHttpRouteDestinationPortOutput
}

// Specifies the port on the host that is being addressed.
type VirtualServiceSpecHttpRouteDestinationPortArgs struct {
	Number pulumi.IntPtrInput `pulumi:"number"`
}

func (VirtualServiceSpecHttpRouteDestinationPortArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpRouteDestinationPort)(nil)).Elem()
}

func (i VirtualServiceSpecHttpRouteDestinationPortArgs) ToVirtualServiceSpecHttpRouteDestinationPortOutput() VirtualServiceSpecHttpRouteDestinationPortOutput {
	return i.ToVirtualServiceSpecHttpRouteDestinationPortOutputWithContext(context.Background())
}

func (i VirtualServiceSpecHttpRouteDestinationPortArgs) ToVirtualServiceSpecHttpRouteDestinationPortOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteDestinationPortOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpRouteDestinationPortOutput)
}

func (i VirtualServiceSpecHttpRouteDestinationPortArgs) ToVirtualServiceSpecHttpRouteDestinationPortPtrOutput() VirtualServiceSpecHttpRouteDestinationPortPtrOutput {
	return i.ToVirtualServiceSpecHttpRouteDestinationPortPtrOutputWithContext(context.Background())
}

func (i VirtualServiceSpecHttpRouteDestinationPortArgs) ToVirtualServiceSpecHttpRouteDestinationPortPtrOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteDestinationPortPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpRouteDestinationPortOutput).ToVirtualServiceSpecHttpRouteDestinationPortPtrOutputWithContext(ctx)
}

// VirtualServiceSpecHttpRouteDestinationPortPtrInput is an input type that accepts VirtualServiceSpecHttpRouteDestinationPortArgs, VirtualServiceSpecHttpRouteDestinationPortPtr and VirtualServiceSpecHttpRouteDestinationPortPtrOutput values.
// You can construct a concrete instance of `VirtualServiceSpecHttpRouteDestinationPortPtrInput` via:
//
//          VirtualServiceSpecHttpRouteDestinationPortArgs{...}
//
//  or:
//
//          nil
type VirtualServiceSpecHttpRouteDestinationPortPtrInput interface {
	pulumi.Input

	ToVirtualServiceSpecHttpRouteDestinationPortPtrOutput() VirtualServiceSpecHttpRouteDestinationPortPtrOutput
	ToVirtualServiceSpecHttpRouteDestinationPortPtrOutputWithContext(context.Context) VirtualServiceSpecHttpRouteDestinationPortPtrOutput
}

type virtualServiceSpecHttpRouteDestinationPortPtrType VirtualServiceSpecHttpRouteDestinationPortArgs

func VirtualServiceSpecHttpRouteDestinationPortPtr(v *VirtualServiceSpecHttpRouteDestinationPortArgs) VirtualServiceSpecHttpRouteDestinationPortPtrInput {
	return (*virtualServiceSpecHttpRouteDestinationPortPtrType)(v)
}

func (*virtualServiceSpecHttpRouteDestinationPortPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualServiceSpecHttpRouteDestinationPort)(nil)).Elem()
}

func (i *virtualServiceSpecHttpRouteDestinationPortPtrType) ToVirtualServiceSpecHttpRouteDestinationPortPtrOutput() VirtualServiceSpecHttpRouteDestinationPortPtrOutput {
	return i.ToVirtualServiceSpecHttpRouteDestinationPortPtrOutputWithContext(context.Background())
}

func (i *virtualServiceSpecHttpRouteDestinationPortPtrType) ToVirtualServiceSpecHttpRouteDestinationPortPtrOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteDestinationPortPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpRouteDestinationPortPtrOutput)
}

// Specifies the port on the host that is being addressed.
type VirtualServiceSpecHttpRouteDestinationPortOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecHttpRouteDestinationPortOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpRouteDestinationPort)(nil)).Elem()
}

func (o VirtualServiceSpecHttpRouteDestinationPortOutput) ToVirtualServiceSpecHttpRouteDestinationPortOutput() VirtualServiceSpecHttpRouteDestinationPortOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteDestinationPortOutput) ToVirtualServiceSpecHttpRouteDestinationPortOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteDestinationPortOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteDestinationPortOutput) ToVirtualServiceSpecHttpRouteDestinationPortPtrOutput() VirtualServiceSpecHttpRouteDestinationPortPtrOutput {
	return o.ToVirtualServiceSpecHttpRouteDestinationPortPtrOutputWithContext(context.Background())
}

func (o VirtualServiceSpecHttpRouteDestinationPortOutput) ToVirtualServiceSpecHttpRouteDestinationPortPtrOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteDestinationPortPtrOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpRouteDestinationPort) *VirtualServiceSpecHttpRouteDestinationPort {
		return &v
	}).(VirtualServiceSpecHttpRouteDestinationPortPtrOutput)
}
func (o VirtualServiceSpecHttpRouteDestinationPortOutput) Number() pulumi.IntPtrOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpRouteDestinationPort) *int { return v.Number }).(pulumi.IntPtrOutput)
}

type VirtualServiceSpecHttpRouteDestinationPortPtrOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecHttpRouteDestinationPortPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualServiceSpecHttpRouteDestinationPort)(nil)).Elem()
}

func (o VirtualServiceSpecHttpRouteDestinationPortPtrOutput) ToVirtualServiceSpecHttpRouteDestinationPortPtrOutput() VirtualServiceSpecHttpRouteDestinationPortPtrOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteDestinationPortPtrOutput) ToVirtualServiceSpecHttpRouteDestinationPortPtrOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteDestinationPortPtrOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteDestinationPortPtrOutput) Elem() VirtualServiceSpecHttpRouteDestinationPortOutput {
	return o.ApplyT(func(v *VirtualServiceSpecHttpRouteDestinationPort) VirtualServiceSpecHttpRouteDestinationPort {
		return *v
	}).(VirtualServiceSpecHttpRouteDestinationPortOutput)
}

func (o VirtualServiceSpecHttpRouteDestinationPortPtrOutput) Number() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *VirtualServiceSpecHttpRouteDestinationPort) *int {
		if v == nil {
			return nil
		}
		return v.Number
	}).(pulumi.IntPtrOutput)
}

type VirtualServiceSpecHttpRouteHeaders struct {
	Request  *VirtualServiceSpecHttpRouteHeadersRequest  `pulumi:"request"`
	Response *VirtualServiceSpecHttpRouteHeadersResponse `pulumi:"response"`
}

// VirtualServiceSpecHttpRouteHeadersInput is an input type that accepts VirtualServiceSpecHttpRouteHeadersArgs and VirtualServiceSpecHttpRouteHeadersOutput values.
// You can construct a concrete instance of `VirtualServiceSpecHttpRouteHeadersInput` via:
//
//          VirtualServiceSpecHttpRouteHeadersArgs{...}
type VirtualServiceSpecHttpRouteHeadersInput interface {
	pulumi.Input

	ToVirtualServiceSpecHttpRouteHeadersOutput() VirtualServiceSpecHttpRouteHeadersOutput
	ToVirtualServiceSpecHttpRouteHeadersOutputWithContext(context.Context) VirtualServiceSpecHttpRouteHeadersOutput
}

type VirtualServiceSpecHttpRouteHeadersArgs struct {
	Request  VirtualServiceSpecHttpRouteHeadersRequestPtrInput  `pulumi:"request"`
	Response VirtualServiceSpecHttpRouteHeadersResponsePtrInput `pulumi:"response"`
}

func (VirtualServiceSpecHttpRouteHeadersArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpRouteHeaders)(nil)).Elem()
}

func (i VirtualServiceSpecHttpRouteHeadersArgs) ToVirtualServiceSpecHttpRouteHeadersOutput() VirtualServiceSpecHttpRouteHeadersOutput {
	return i.ToVirtualServiceSpecHttpRouteHeadersOutputWithContext(context.Background())
}

func (i VirtualServiceSpecHttpRouteHeadersArgs) ToVirtualServiceSpecHttpRouteHeadersOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpRouteHeadersOutput)
}

func (i VirtualServiceSpecHttpRouteHeadersArgs) ToVirtualServiceSpecHttpRouteHeadersPtrOutput() VirtualServiceSpecHttpRouteHeadersPtrOutput {
	return i.ToVirtualServiceSpecHttpRouteHeadersPtrOutputWithContext(context.Background())
}

func (i VirtualServiceSpecHttpRouteHeadersArgs) ToVirtualServiceSpecHttpRouteHeadersPtrOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpRouteHeadersOutput).ToVirtualServiceSpecHttpRouteHeadersPtrOutputWithContext(ctx)
}

// VirtualServiceSpecHttpRouteHeadersPtrInput is an input type that accepts VirtualServiceSpecHttpRouteHeadersArgs, VirtualServiceSpecHttpRouteHeadersPtr and VirtualServiceSpecHttpRouteHeadersPtrOutput values.
// You can construct a concrete instance of `VirtualServiceSpecHttpRouteHeadersPtrInput` via:
//
//          VirtualServiceSpecHttpRouteHeadersArgs{...}
//
//  or:
//
//          nil
type VirtualServiceSpecHttpRouteHeadersPtrInput interface {
	pulumi.Input

	ToVirtualServiceSpecHttpRouteHeadersPtrOutput() VirtualServiceSpecHttpRouteHeadersPtrOutput
	ToVirtualServiceSpecHttpRouteHeadersPtrOutputWithContext(context.Context) VirtualServiceSpecHttpRouteHeadersPtrOutput
}

type virtualServiceSpecHttpRouteHeadersPtrType VirtualServiceSpecHttpRouteHeadersArgs

func VirtualServiceSpecHttpRouteHeadersPtr(v *VirtualServiceSpecHttpRouteHeadersArgs) VirtualServiceSpecHttpRouteHeadersPtrInput {
	return (*virtualServiceSpecHttpRouteHeadersPtrType)(v)
}

func (*virtualServiceSpecHttpRouteHeadersPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualServiceSpecHttpRouteHeaders)(nil)).Elem()
}

func (i *virtualServiceSpecHttpRouteHeadersPtrType) ToVirtualServiceSpecHttpRouteHeadersPtrOutput() VirtualServiceSpecHttpRouteHeadersPtrOutput {
	return i.ToVirtualServiceSpecHttpRouteHeadersPtrOutputWithContext(context.Background())
}

func (i *virtualServiceSpecHttpRouteHeadersPtrType) ToVirtualServiceSpecHttpRouteHeadersPtrOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpRouteHeadersPtrOutput)
}

type VirtualServiceSpecHttpRouteHeadersOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecHttpRouteHeadersOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpRouteHeaders)(nil)).Elem()
}

func (o VirtualServiceSpecHttpRouteHeadersOutput) ToVirtualServiceSpecHttpRouteHeadersOutput() VirtualServiceSpecHttpRouteHeadersOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteHeadersOutput) ToVirtualServiceSpecHttpRouteHeadersOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteHeadersOutput) ToVirtualServiceSpecHttpRouteHeadersPtrOutput() VirtualServiceSpecHttpRouteHeadersPtrOutput {
	return o.ToVirtualServiceSpecHttpRouteHeadersPtrOutputWithContext(context.Background())
}

func (o VirtualServiceSpecHttpRouteHeadersOutput) ToVirtualServiceSpecHttpRouteHeadersPtrOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersPtrOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpRouteHeaders) *VirtualServiceSpecHttpRouteHeaders {
		return &v
	}).(VirtualServiceSpecHttpRouteHeadersPtrOutput)
}
func (o VirtualServiceSpecHttpRouteHeadersOutput) Request() VirtualServiceSpecHttpRouteHeadersRequestPtrOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpRouteHeaders) *VirtualServiceSpecHttpRouteHeadersRequest {
		return v.Request
	}).(VirtualServiceSpecHttpRouteHeadersRequestPtrOutput)
}

func (o VirtualServiceSpecHttpRouteHeadersOutput) Response() VirtualServiceSpecHttpRouteHeadersResponsePtrOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpRouteHeaders) *VirtualServiceSpecHttpRouteHeadersResponse {
		return v.Response
	}).(VirtualServiceSpecHttpRouteHeadersResponsePtrOutput)
}

type VirtualServiceSpecHttpRouteHeadersPtrOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecHttpRouteHeadersPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualServiceSpecHttpRouteHeaders)(nil)).Elem()
}

func (o VirtualServiceSpecHttpRouteHeadersPtrOutput) ToVirtualServiceSpecHttpRouteHeadersPtrOutput() VirtualServiceSpecHttpRouteHeadersPtrOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteHeadersPtrOutput) ToVirtualServiceSpecHttpRouteHeadersPtrOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersPtrOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteHeadersPtrOutput) Elem() VirtualServiceSpecHttpRouteHeadersOutput {
	return o.ApplyT(func(v *VirtualServiceSpecHttpRouteHeaders) VirtualServiceSpecHttpRouteHeaders { return *v }).(VirtualServiceSpecHttpRouteHeadersOutput)
}

func (o VirtualServiceSpecHttpRouteHeadersPtrOutput) Request() VirtualServiceSpecHttpRouteHeadersRequestPtrOutput {
	return o.ApplyT(func(v *VirtualServiceSpecHttpRouteHeaders) *VirtualServiceSpecHttpRouteHeadersRequest {
		if v == nil {
			return nil
		}
		return v.Request
	}).(VirtualServiceSpecHttpRouteHeadersRequestPtrOutput)
}

func (o VirtualServiceSpecHttpRouteHeadersPtrOutput) Response() VirtualServiceSpecHttpRouteHeadersResponsePtrOutput {
	return o.ApplyT(func(v *VirtualServiceSpecHttpRouteHeaders) *VirtualServiceSpecHttpRouteHeadersResponse {
		if v == nil {
			return nil
		}
		return v.Response
	}).(VirtualServiceSpecHttpRouteHeadersResponsePtrOutput)
}

type VirtualServiceSpecHttpRouteHeadersRequest struct {
	Add    map[string]string `pulumi:"add"`
	Remove []string          `pulumi:"remove"`
	Set    map[string]string `pulumi:"set"`
}

// VirtualServiceSpecHttpRouteHeadersRequestInput is an input type that accepts VirtualServiceSpecHttpRouteHeadersRequestArgs and VirtualServiceSpecHttpRouteHeadersRequestOutput values.
// You can construct a concrete instance of `VirtualServiceSpecHttpRouteHeadersRequestInput` via:
//
//          VirtualServiceSpecHttpRouteHeadersRequestArgs{...}
type VirtualServiceSpecHttpRouteHeadersRequestInput interface {
	pulumi.Input

	ToVirtualServiceSpecHttpRouteHeadersRequestOutput() VirtualServiceSpecHttpRouteHeadersRequestOutput
	ToVirtualServiceSpecHttpRouteHeadersRequestOutputWithContext(context.Context) VirtualServiceSpecHttpRouteHeadersRequestOutput
}

type VirtualServiceSpecHttpRouteHeadersRequestArgs struct {
	Add    pulumi.StringMapInput   `pulumi:"add"`
	Remove pulumi.StringArrayInput `pulumi:"remove"`
	Set    pulumi.StringMapInput   `pulumi:"set"`
}

func (VirtualServiceSpecHttpRouteHeadersRequestArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpRouteHeadersRequest)(nil)).Elem()
}

func (i VirtualServiceSpecHttpRouteHeadersRequestArgs) ToVirtualServiceSpecHttpRouteHeadersRequestOutput() VirtualServiceSpecHttpRouteHeadersRequestOutput {
	return i.ToVirtualServiceSpecHttpRouteHeadersRequestOutputWithContext(context.Background())
}

func (i VirtualServiceSpecHttpRouteHeadersRequestArgs) ToVirtualServiceSpecHttpRouteHeadersRequestOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersRequestOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpRouteHeadersRequestOutput)
}

func (i VirtualServiceSpecHttpRouteHeadersRequestArgs) ToVirtualServiceSpecHttpRouteHeadersRequestPtrOutput() VirtualServiceSpecHttpRouteHeadersRequestPtrOutput {
	return i.ToVirtualServiceSpecHttpRouteHeadersRequestPtrOutputWithContext(context.Background())
}

func (i VirtualServiceSpecHttpRouteHeadersRequestArgs) ToVirtualServiceSpecHttpRouteHeadersRequestPtrOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersRequestPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpRouteHeadersRequestOutput).ToVirtualServiceSpecHttpRouteHeadersRequestPtrOutputWithContext(ctx)
}

// VirtualServiceSpecHttpRouteHeadersRequestPtrInput is an input type that accepts VirtualServiceSpecHttpRouteHeadersRequestArgs, VirtualServiceSpecHttpRouteHeadersRequestPtr and VirtualServiceSpecHttpRouteHeadersRequestPtrOutput values.
// You can construct a concrete instance of `VirtualServiceSpecHttpRouteHeadersRequestPtrInput` via:
//
//          VirtualServiceSpecHttpRouteHeadersRequestArgs{...}
//
//  or:
//
//          nil
type VirtualServiceSpecHttpRouteHeadersRequestPtrInput interface {
	pulumi.Input

	ToVirtualServiceSpecHttpRouteHeadersRequestPtrOutput() VirtualServiceSpecHttpRouteHeadersRequestPtrOutput
	ToVirtualServiceSpecHttpRouteHeadersRequestPtrOutputWithContext(context.Context) VirtualServiceSpecHttpRouteHeadersRequestPtrOutput
}

type virtualServiceSpecHttpRouteHeadersRequestPtrType VirtualServiceSpecHttpRouteHeadersRequestArgs

func VirtualServiceSpecHttpRouteHeadersRequestPtr(v *VirtualServiceSpecHttpRouteHeadersRequestArgs) VirtualServiceSpecHttpRouteHeadersRequestPtrInput {
	return (*virtualServiceSpecHttpRouteHeadersRequestPtrType)(v)
}

func (*virtualServiceSpecHttpRouteHeadersRequestPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualServiceSpecHttpRouteHeadersRequest)(nil)).Elem()
}

func (i *virtualServiceSpecHttpRouteHeadersRequestPtrType) ToVirtualServiceSpecHttpRouteHeadersRequestPtrOutput() VirtualServiceSpecHttpRouteHeadersRequestPtrOutput {
	return i.ToVirtualServiceSpecHttpRouteHeadersRequestPtrOutputWithContext(context.Background())
}

func (i *virtualServiceSpecHttpRouteHeadersRequestPtrType) ToVirtualServiceSpecHttpRouteHeadersRequestPtrOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersRequestPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpRouteHeadersRequestPtrOutput)
}

type VirtualServiceSpecHttpRouteHeadersRequestOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecHttpRouteHeadersRequestOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpRouteHeadersRequest)(nil)).Elem()
}

func (o VirtualServiceSpecHttpRouteHeadersRequestOutput) ToVirtualServiceSpecHttpRouteHeadersRequestOutput() VirtualServiceSpecHttpRouteHeadersRequestOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteHeadersRequestOutput) ToVirtualServiceSpecHttpRouteHeadersRequestOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersRequestOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteHeadersRequestOutput) ToVirtualServiceSpecHttpRouteHeadersRequestPtrOutput() VirtualServiceSpecHttpRouteHeadersRequestPtrOutput {
	return o.ToVirtualServiceSpecHttpRouteHeadersRequestPtrOutputWithContext(context.Background())
}

func (o VirtualServiceSpecHttpRouteHeadersRequestOutput) ToVirtualServiceSpecHttpRouteHeadersRequestPtrOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersRequestPtrOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpRouteHeadersRequest) *VirtualServiceSpecHttpRouteHeadersRequest {
		return &v
	}).(VirtualServiceSpecHttpRouteHeadersRequestPtrOutput)
}
func (o VirtualServiceSpecHttpRouteHeadersRequestOutput) Add() pulumi.StringMapOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpRouteHeadersRequest) map[string]string { return v.Add }).(pulumi.StringMapOutput)
}

func (o VirtualServiceSpecHttpRouteHeadersRequestOutput) Remove() pulumi.StringArrayOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpRouteHeadersRequest) []string { return v.Remove }).(pulumi.StringArrayOutput)
}

func (o VirtualServiceSpecHttpRouteHeadersRequestOutput) Set() pulumi.StringMapOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpRouteHeadersRequest) map[string]string { return v.Set }).(pulumi.StringMapOutput)
}

type VirtualServiceSpecHttpRouteHeadersRequestPtrOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecHttpRouteHeadersRequestPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualServiceSpecHttpRouteHeadersRequest)(nil)).Elem()
}

func (o VirtualServiceSpecHttpRouteHeadersRequestPtrOutput) ToVirtualServiceSpecHttpRouteHeadersRequestPtrOutput() VirtualServiceSpecHttpRouteHeadersRequestPtrOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteHeadersRequestPtrOutput) ToVirtualServiceSpecHttpRouteHeadersRequestPtrOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersRequestPtrOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteHeadersRequestPtrOutput) Elem() VirtualServiceSpecHttpRouteHeadersRequestOutput {
	return o.ApplyT(func(v *VirtualServiceSpecHttpRouteHeadersRequest) VirtualServiceSpecHttpRouteHeadersRequest {
		return *v
	}).(VirtualServiceSpecHttpRouteHeadersRequestOutput)
}

func (o VirtualServiceSpecHttpRouteHeadersRequestPtrOutput) Add() pulumi.StringMapOutput {
	return o.ApplyT(func(v *VirtualServiceSpecHttpRouteHeadersRequest) map[string]string {
		if v == nil {
			return nil
		}
		return v.Add
	}).(pulumi.StringMapOutput)
}

func (o VirtualServiceSpecHttpRouteHeadersRequestPtrOutput) Remove() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *VirtualServiceSpecHttpRouteHeadersRequest) []string {
		if v == nil {
			return nil
		}
		return v.Remove
	}).(pulumi.StringArrayOutput)
}

func (o VirtualServiceSpecHttpRouteHeadersRequestPtrOutput) Set() pulumi.StringMapOutput {
	return o.ApplyT(func(v *VirtualServiceSpecHttpRouteHeadersRequest) map[string]string {
		if v == nil {
			return nil
		}
		return v.Set
	}).(pulumi.StringMapOutput)
}

type VirtualServiceSpecHttpRouteHeadersRequestAdd struct {
}

// VirtualServiceSpecHttpRouteHeadersRequestAddInput is an input type that accepts VirtualServiceSpecHttpRouteHeadersRequestAddArgs and VirtualServiceSpecHttpRouteHeadersRequestAddOutput values.
// You can construct a concrete instance of `VirtualServiceSpecHttpRouteHeadersRequestAddInput` via:
//
//          VirtualServiceSpecHttpRouteHeadersRequestAddArgs{...}
type VirtualServiceSpecHttpRouteHeadersRequestAddInput interface {
	pulumi.Input

	ToVirtualServiceSpecHttpRouteHeadersRequestAddOutput() VirtualServiceSpecHttpRouteHeadersRequestAddOutput
	ToVirtualServiceSpecHttpRouteHeadersRequestAddOutputWithContext(context.Context) VirtualServiceSpecHttpRouteHeadersRequestAddOutput
}

type VirtualServiceSpecHttpRouteHeadersRequestAddArgs struct {
}

func (VirtualServiceSpecHttpRouteHeadersRequestAddArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpRouteHeadersRequestAdd)(nil)).Elem()
}

func (i VirtualServiceSpecHttpRouteHeadersRequestAddArgs) ToVirtualServiceSpecHttpRouteHeadersRequestAddOutput() VirtualServiceSpecHttpRouteHeadersRequestAddOutput {
	return i.ToVirtualServiceSpecHttpRouteHeadersRequestAddOutputWithContext(context.Background())
}

func (i VirtualServiceSpecHttpRouteHeadersRequestAddArgs) ToVirtualServiceSpecHttpRouteHeadersRequestAddOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersRequestAddOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpRouteHeadersRequestAddOutput)
}

type VirtualServiceSpecHttpRouteHeadersRequestAddOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecHttpRouteHeadersRequestAddOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpRouteHeadersRequestAdd)(nil)).Elem()
}

func (o VirtualServiceSpecHttpRouteHeadersRequestAddOutput) ToVirtualServiceSpecHttpRouteHeadersRequestAddOutput() VirtualServiceSpecHttpRouteHeadersRequestAddOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteHeadersRequestAddOutput) ToVirtualServiceSpecHttpRouteHeadersRequestAddOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersRequestAddOutput {
	return o
}

type VirtualServiceSpecHttpRouteHeadersRequestSet struct {
}

// VirtualServiceSpecHttpRouteHeadersRequestSetInput is an input type that accepts VirtualServiceSpecHttpRouteHeadersRequestSetArgs and VirtualServiceSpecHttpRouteHeadersRequestSetOutput values.
// You can construct a concrete instance of `VirtualServiceSpecHttpRouteHeadersRequestSetInput` via:
//
//          VirtualServiceSpecHttpRouteHeadersRequestSetArgs{...}
type VirtualServiceSpecHttpRouteHeadersRequestSetInput interface {
	pulumi.Input

	ToVirtualServiceSpecHttpRouteHeadersRequestSetOutput() VirtualServiceSpecHttpRouteHeadersRequestSetOutput
	ToVirtualServiceSpecHttpRouteHeadersRequestSetOutputWithContext(context.Context) VirtualServiceSpecHttpRouteHeadersRequestSetOutput
}

type VirtualServiceSpecHttpRouteHeadersRequestSetArgs struct {
}

func (VirtualServiceSpecHttpRouteHeadersRequestSetArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpRouteHeadersRequestSet)(nil)).Elem()
}

func (i VirtualServiceSpecHttpRouteHeadersRequestSetArgs) ToVirtualServiceSpecHttpRouteHeadersRequestSetOutput() VirtualServiceSpecHttpRouteHeadersRequestSetOutput {
	return i.ToVirtualServiceSpecHttpRouteHeadersRequestSetOutputWithContext(context.Background())
}

func (i VirtualServiceSpecHttpRouteHeadersRequestSetArgs) ToVirtualServiceSpecHttpRouteHeadersRequestSetOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersRequestSetOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpRouteHeadersRequestSetOutput)
}

type VirtualServiceSpecHttpRouteHeadersRequestSetOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecHttpRouteHeadersRequestSetOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpRouteHeadersRequestSet)(nil)).Elem()
}

func (o VirtualServiceSpecHttpRouteHeadersRequestSetOutput) ToVirtualServiceSpecHttpRouteHeadersRequestSetOutput() VirtualServiceSpecHttpRouteHeadersRequestSetOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteHeadersRequestSetOutput) ToVirtualServiceSpecHttpRouteHeadersRequestSetOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersRequestSetOutput {
	return o
}

type VirtualServiceSpecHttpRouteHeadersResponse struct {
	Add    map[string]string `pulumi:"add"`
	Remove []string          `pulumi:"remove"`
	Set    map[string]string `pulumi:"set"`
}

// VirtualServiceSpecHttpRouteHeadersResponseInput is an input type that accepts VirtualServiceSpecHttpRouteHeadersResponseArgs and VirtualServiceSpecHttpRouteHeadersResponseOutput values.
// You can construct a concrete instance of `VirtualServiceSpecHttpRouteHeadersResponseInput` via:
//
//          VirtualServiceSpecHttpRouteHeadersResponseArgs{...}
type VirtualServiceSpecHttpRouteHeadersResponseInput interface {
	pulumi.Input

	ToVirtualServiceSpecHttpRouteHeadersResponseOutput() VirtualServiceSpecHttpRouteHeadersResponseOutput
	ToVirtualServiceSpecHttpRouteHeadersResponseOutputWithContext(context.Context) VirtualServiceSpecHttpRouteHeadersResponseOutput
}

type VirtualServiceSpecHttpRouteHeadersResponseArgs struct {
	Add    pulumi.StringMapInput   `pulumi:"add"`
	Remove pulumi.StringArrayInput `pulumi:"remove"`
	Set    pulumi.StringMapInput   `pulumi:"set"`
}

func (VirtualServiceSpecHttpRouteHeadersResponseArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpRouteHeadersResponse)(nil)).Elem()
}

func (i VirtualServiceSpecHttpRouteHeadersResponseArgs) ToVirtualServiceSpecHttpRouteHeadersResponseOutput() VirtualServiceSpecHttpRouteHeadersResponseOutput {
	return i.ToVirtualServiceSpecHttpRouteHeadersResponseOutputWithContext(context.Background())
}

func (i VirtualServiceSpecHttpRouteHeadersResponseArgs) ToVirtualServiceSpecHttpRouteHeadersResponseOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersResponseOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpRouteHeadersResponseOutput)
}

func (i VirtualServiceSpecHttpRouteHeadersResponseArgs) ToVirtualServiceSpecHttpRouteHeadersResponsePtrOutput() VirtualServiceSpecHttpRouteHeadersResponsePtrOutput {
	return i.ToVirtualServiceSpecHttpRouteHeadersResponsePtrOutputWithContext(context.Background())
}

func (i VirtualServiceSpecHttpRouteHeadersResponseArgs) ToVirtualServiceSpecHttpRouteHeadersResponsePtrOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersResponsePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpRouteHeadersResponseOutput).ToVirtualServiceSpecHttpRouteHeadersResponsePtrOutputWithContext(ctx)
}

// VirtualServiceSpecHttpRouteHeadersResponsePtrInput is an input type that accepts VirtualServiceSpecHttpRouteHeadersResponseArgs, VirtualServiceSpecHttpRouteHeadersResponsePtr and VirtualServiceSpecHttpRouteHeadersResponsePtrOutput values.
// You can construct a concrete instance of `VirtualServiceSpecHttpRouteHeadersResponsePtrInput` via:
//
//          VirtualServiceSpecHttpRouteHeadersResponseArgs{...}
//
//  or:
//
//          nil
type VirtualServiceSpecHttpRouteHeadersResponsePtrInput interface {
	pulumi.Input

	ToVirtualServiceSpecHttpRouteHeadersResponsePtrOutput() VirtualServiceSpecHttpRouteHeadersResponsePtrOutput
	ToVirtualServiceSpecHttpRouteHeadersResponsePtrOutputWithContext(context.Context) VirtualServiceSpecHttpRouteHeadersResponsePtrOutput
}

type virtualServiceSpecHttpRouteHeadersResponsePtrType VirtualServiceSpecHttpRouteHeadersResponseArgs

func VirtualServiceSpecHttpRouteHeadersResponsePtr(v *VirtualServiceSpecHttpRouteHeadersResponseArgs) VirtualServiceSpecHttpRouteHeadersResponsePtrInput {
	return (*virtualServiceSpecHttpRouteHeadersResponsePtrType)(v)
}

func (*virtualServiceSpecHttpRouteHeadersResponsePtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualServiceSpecHttpRouteHeadersResponse)(nil)).Elem()
}

func (i *virtualServiceSpecHttpRouteHeadersResponsePtrType) ToVirtualServiceSpecHttpRouteHeadersResponsePtrOutput() VirtualServiceSpecHttpRouteHeadersResponsePtrOutput {
	return i.ToVirtualServiceSpecHttpRouteHeadersResponsePtrOutputWithContext(context.Background())
}

func (i *virtualServiceSpecHttpRouteHeadersResponsePtrType) ToVirtualServiceSpecHttpRouteHeadersResponsePtrOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersResponsePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpRouteHeadersResponsePtrOutput)
}

type VirtualServiceSpecHttpRouteHeadersResponseOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecHttpRouteHeadersResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpRouteHeadersResponse)(nil)).Elem()
}

func (o VirtualServiceSpecHttpRouteHeadersResponseOutput) ToVirtualServiceSpecHttpRouteHeadersResponseOutput() VirtualServiceSpecHttpRouteHeadersResponseOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteHeadersResponseOutput) ToVirtualServiceSpecHttpRouteHeadersResponseOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersResponseOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteHeadersResponseOutput) ToVirtualServiceSpecHttpRouteHeadersResponsePtrOutput() VirtualServiceSpecHttpRouteHeadersResponsePtrOutput {
	return o.ToVirtualServiceSpecHttpRouteHeadersResponsePtrOutputWithContext(context.Background())
}

func (o VirtualServiceSpecHttpRouteHeadersResponseOutput) ToVirtualServiceSpecHttpRouteHeadersResponsePtrOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersResponsePtrOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpRouteHeadersResponse) *VirtualServiceSpecHttpRouteHeadersResponse {
		return &v
	}).(VirtualServiceSpecHttpRouteHeadersResponsePtrOutput)
}
func (o VirtualServiceSpecHttpRouteHeadersResponseOutput) Add() pulumi.StringMapOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpRouteHeadersResponse) map[string]string { return v.Add }).(pulumi.StringMapOutput)
}

func (o VirtualServiceSpecHttpRouteHeadersResponseOutput) Remove() pulumi.StringArrayOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpRouteHeadersResponse) []string { return v.Remove }).(pulumi.StringArrayOutput)
}

func (o VirtualServiceSpecHttpRouteHeadersResponseOutput) Set() pulumi.StringMapOutput {
	return o.ApplyT(func(v VirtualServiceSpecHttpRouteHeadersResponse) map[string]string { return v.Set }).(pulumi.StringMapOutput)
}

type VirtualServiceSpecHttpRouteHeadersResponsePtrOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecHttpRouteHeadersResponsePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualServiceSpecHttpRouteHeadersResponse)(nil)).Elem()
}

func (o VirtualServiceSpecHttpRouteHeadersResponsePtrOutput) ToVirtualServiceSpecHttpRouteHeadersResponsePtrOutput() VirtualServiceSpecHttpRouteHeadersResponsePtrOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteHeadersResponsePtrOutput) ToVirtualServiceSpecHttpRouteHeadersResponsePtrOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersResponsePtrOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteHeadersResponsePtrOutput) Elem() VirtualServiceSpecHttpRouteHeadersResponseOutput {
	return o.ApplyT(func(v *VirtualServiceSpecHttpRouteHeadersResponse) VirtualServiceSpecHttpRouteHeadersResponse {
		return *v
	}).(VirtualServiceSpecHttpRouteHeadersResponseOutput)
}

func (o VirtualServiceSpecHttpRouteHeadersResponsePtrOutput) Add() pulumi.StringMapOutput {
	return o.ApplyT(func(v *VirtualServiceSpecHttpRouteHeadersResponse) map[string]string {
		if v == nil {
			return nil
		}
		return v.Add
	}).(pulumi.StringMapOutput)
}

func (o VirtualServiceSpecHttpRouteHeadersResponsePtrOutput) Remove() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *VirtualServiceSpecHttpRouteHeadersResponse) []string {
		if v == nil {
			return nil
		}
		return v.Remove
	}).(pulumi.StringArrayOutput)
}

func (o VirtualServiceSpecHttpRouteHeadersResponsePtrOutput) Set() pulumi.StringMapOutput {
	return o.ApplyT(func(v *VirtualServiceSpecHttpRouteHeadersResponse) map[string]string {
		if v == nil {
			return nil
		}
		return v.Set
	}).(pulumi.StringMapOutput)
}

type VirtualServiceSpecHttpRouteHeadersResponseAdd struct {
}

// VirtualServiceSpecHttpRouteHeadersResponseAddInput is an input type that accepts VirtualServiceSpecHttpRouteHeadersResponseAddArgs and VirtualServiceSpecHttpRouteHeadersResponseAddOutput values.
// You can construct a concrete instance of `VirtualServiceSpecHttpRouteHeadersResponseAddInput` via:
//
//          VirtualServiceSpecHttpRouteHeadersResponseAddArgs{...}
type VirtualServiceSpecHttpRouteHeadersResponseAddInput interface {
	pulumi.Input

	ToVirtualServiceSpecHttpRouteHeadersResponseAddOutput() VirtualServiceSpecHttpRouteHeadersResponseAddOutput
	ToVirtualServiceSpecHttpRouteHeadersResponseAddOutputWithContext(context.Context) VirtualServiceSpecHttpRouteHeadersResponseAddOutput
}

type VirtualServiceSpecHttpRouteHeadersResponseAddArgs struct {
}

func (VirtualServiceSpecHttpRouteHeadersResponseAddArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpRouteHeadersResponseAdd)(nil)).Elem()
}

func (i VirtualServiceSpecHttpRouteHeadersResponseAddArgs) ToVirtualServiceSpecHttpRouteHeadersResponseAddOutput() VirtualServiceSpecHttpRouteHeadersResponseAddOutput {
	return i.ToVirtualServiceSpecHttpRouteHeadersResponseAddOutputWithContext(context.Background())
}

func (i VirtualServiceSpecHttpRouteHeadersResponseAddArgs) ToVirtualServiceSpecHttpRouteHeadersResponseAddOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersResponseAddOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpRouteHeadersResponseAddOutput)
}

type VirtualServiceSpecHttpRouteHeadersResponseAddOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecHttpRouteHeadersResponseAddOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpRouteHeadersResponseAdd)(nil)).Elem()
}

func (o VirtualServiceSpecHttpRouteHeadersResponseAddOutput) ToVirtualServiceSpecHttpRouteHeadersResponseAddOutput() VirtualServiceSpecHttpRouteHeadersResponseAddOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteHeadersResponseAddOutput) ToVirtualServiceSpecHttpRouteHeadersResponseAddOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersResponseAddOutput {
	return o
}

type VirtualServiceSpecHttpRouteHeadersResponseSet struct {
}

// VirtualServiceSpecHttpRouteHeadersResponseSetInput is an input type that accepts VirtualServiceSpecHttpRouteHeadersResponseSetArgs and VirtualServiceSpecHttpRouteHeadersResponseSetOutput values.
// You can construct a concrete instance of `VirtualServiceSpecHttpRouteHeadersResponseSetInput` via:
//
//          VirtualServiceSpecHttpRouteHeadersResponseSetArgs{...}
type VirtualServiceSpecHttpRouteHeadersResponseSetInput interface {
	pulumi.Input

	ToVirtualServiceSpecHttpRouteHeadersResponseSetOutput() VirtualServiceSpecHttpRouteHeadersResponseSetOutput
	ToVirtualServiceSpecHttpRouteHeadersResponseSetOutputWithContext(context.Context) VirtualServiceSpecHttpRouteHeadersResponseSetOutput
}

type VirtualServiceSpecHttpRouteHeadersResponseSetArgs struct {
}

func (VirtualServiceSpecHttpRouteHeadersResponseSetArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpRouteHeadersResponseSet)(nil)).Elem()
}

func (i VirtualServiceSpecHttpRouteHeadersResponseSetArgs) ToVirtualServiceSpecHttpRouteHeadersResponseSetOutput() VirtualServiceSpecHttpRouteHeadersResponseSetOutput {
	return i.ToVirtualServiceSpecHttpRouteHeadersResponseSetOutputWithContext(context.Background())
}

func (i VirtualServiceSpecHttpRouteHeadersResponseSetArgs) ToVirtualServiceSpecHttpRouteHeadersResponseSetOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersResponseSetOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualServiceSpecHttpRouteHeadersResponseSetOutput)
}

type VirtualServiceSpecHttpRouteHeadersResponseSetOutput struct{ *pulumi.OutputState }

func (VirtualServiceSpecHttpRouteHeadersResponseSetOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VirtualServiceSpecHttpRouteHeadersResponseSet)(nil)).Elem()
}

func (o VirtualServiceSpecHttpRouteHeadersResponseSetOutput) ToVirtualServiceSpecHttpRouteHeadersResponseSetOutput() VirtualServiceSpecHttpRouteHeadersResponseSetOutput {
	return o
}

func (o VirtualServiceSpecHttpRouteHeadersResponseSetOutput) ToVirtualServiceSpecHttpRouteHeadersResponseSetOutputWithContext(ctx context.Context) VirtualServiceSpecHttpRouteHeadersResponseSetOutput {
	return o
}

func init() {
	pulumi.RegisterOutputType(VirtualServiceTypeOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecPtrOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecHttpOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecHttpArrayOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecHttpMatchOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecHttpMatchArrayOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecHttpMatchHeadersOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecHttpMatchQueryParamsOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecHttpMatchSourceLabelsOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecHttpMatchWithoutHeadersOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecHttpRouteOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecHttpRouteArrayOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecHttpRouteDestinationOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecHttpRouteDestinationPtrOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecHttpRouteDestinationPortOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecHttpRouteDestinationPortPtrOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecHttpRouteHeadersOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecHttpRouteHeadersPtrOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecHttpRouteHeadersRequestOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecHttpRouteHeadersRequestPtrOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecHttpRouteHeadersRequestAddOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecHttpRouteHeadersRequestSetOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecHttpRouteHeadersResponseOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecHttpRouteHeadersResponsePtrOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecHttpRouteHeadersResponseAddOutput{})
	pulumi.RegisterOutputType(VirtualServiceSpecHttpRouteHeadersResponseSetOutput{})
}
